Random randInt = new Random();
Random randFColour = new Random();
Random randBColour = new Random();
int fNext = randFColour.Next(1, 17);
if (fNext == 1) Console.ForegroundColor = ConsoleColor.Black;
if (fNext == 2) Console.ForegroundColor = ConsoleColor.DarkBlue;
if (fNext == 3) Console.ForegroundColor = ConsoleColor.DarkGreen;
if (fNext == 4) Console.ForegroundColor = ConsoleColor.DarkCyan;
if (fNext == 5) Console.ForegroundColor = ConsoleColor.DarkRed;
if (fNext == 6) Console.ForegroundColor = ConsoleColor.DarkMagenta;
if (fNext == 7) Console.ForegroundColor = ConsoleColor.DarkYellow;
if (fNext == 8) Console.ForegroundColor = ConsoleColor.Gray;
if (fNext == 9) Console.ForegroundColor = ConsoleColor.DarkGray;
if (fNext == 10) Console.ForegroundColor = ConsoleColor.Blue;
if (fNext == 11) Console.ForegroundColor = ConsoleColor.Green;
if (fNext == 12) Console.ForegroundColor = ConsoleColor.Cyan;
if (fNext == 13) Console.ForegroundColor = ConsoleColor.Red;
if (fNext == 14) Console.ForegroundColor = ConsoleColor.Magenta;
if (fNext == 15) Console.ForegroundColor = ConsoleColor.Yellow;
if (fNext == 16) Console.ForegroundColor = ConsoleColor.White;
int bNext = randFColour.Next(1, 17);
if (bNext == 1) Console.BackgroundColor = ConsoleColor.Black;
if (bNext == 2) Console.BackgroundColor = ConsoleColor.DarkBlue;
if (bNext == 3) Console.BackgroundColor = ConsoleColor.DarkGreen;
if (bNext == 4) Console.BackgroundColor = ConsoleColor.DarkCyan;
if (bNext == 5) Console.BackgroundColor = ConsoleColor.DarkRed;
if (bNext == 6) Console.BackgroundColor = ConsoleColor.DarkMagenta;
if (bNext == 7) Console.BackgroundColor = ConsoleColor.DarkYellow;
if (bNext == 8) Console.BackgroundColor = ConsoleColor.Gray;
if (bNext == 9) Console.BackgroundColor = ConsoleColor.DarkGray;
if (bNext == 10) Console.BackgroundColor = ConsoleColor.Blue;
if (bNext == 11) Console.BackgroundColor = ConsoleColor.Green;
if (bNext == 12) Console.BackgroundColor = ConsoleColor.Cyan;
if (bNext == 13) Console.BackgroundColor = ConsoleColor.Red;
if (bNext == 14) Console.BackgroundColor = ConsoleColor.Magenta;
if (bNext == 15) Console.BackgroundColor = ConsoleColor.Yellow;
if (bNext == 16) Console.BackgroundColor = ConsoleColor.White;

int next = randInt.Next(1, 5);
if (next == 1) Console.WriteLine("Hello, World!");
if (next == 2) Console.WriteLine("World, Hello!");
if (next == 3) Console.WriteLine(". Hello World!");
if (next == 4)Console.WriteLine("!Dlrow ,Olleh");

